/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.crocheters.views;

import com.crocheters.model.crochetModel;
import java.util.LinkedList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Ekata Baral
 * LMUID 23048589
 */
public class crochetApp extends javax.swing.JFrame {
    
    private List<crochetModel> productList;
    private java.awt.CardLayout cardLayout;

    /**
     * Creates new form crochetApp
     */
    public crochetApp() {
        initComponents();
        
        layoutInitialize();
        dataInitialize();
        forProgressBar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlTab = new javax.swing.JPanel();
        tabbedPane = new javax.swing.JTabbedPane();
        pnlAdminControls = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblBrandInfo = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtBrandInfo = new javax.swing.JTextArea();
        pnlDisplayProducts = new javax.swing.JPanel();
        lblGrannyCardigan = new javax.swing.JLabel();
        lblHalfSweater = new javax.swing.JLabel();
        lblCosyGreenSweater = new javax.swing.JLabel();
        lblGrannySquareCardigan = new javax.swing.JLabel();
        pnlAllproducts = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProducts = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        pnlAddproducts = new javax.swing.JPanel();
        pnlForm = new javax.swing.JPanel();
        txtProdid = new javax.swing.JTextField();
        txtProdName = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        spinStock = new javax.swing.JSpinner();
        btnUpdate = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        checkRepair = new javax.swing.JCheckBox();
        boxCategory = new javax.swing.JComboBox<>();
        boxYarnType = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        lblTagline = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        pnlLogin = new javax.swing.JPanel();
        pnlLoginInfo = new javax.swing.JPanel();
        lblSignin = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        txtUserName = new javax.swing.JTextField();
        lblLoginInfo = new javax.swing.JLabel();
        lblForgotPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lblError = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        pnlLoadScreen = new javax.swing.JPanel();
        progressBar = new javax.swing.JProgressBar();
        lblLoading = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblLoading2 = new javax.swing.JLabel();
        lblLoading5 = new javax.swing.JLabel();

        pnlMain.setBackground(new java.awt.Color(82, 91, 68));
        pnlMain.setMaximumSize(new java.awt.Dimension(900, 600));
        pnlMain.setMinimumSize(new java.awt.Dimension(900, 600));
        pnlMain.setPreferredSize(new java.awt.Dimension(900, 600));

        pnlTab.setBackground(new java.awt.Color(248, 247, 244));

        tabbedPane.setBackground(new java.awt.Color(248, 247, 244));
        tabbedPane.setMaximumSize(new java.awt.Dimension(900, 585));
        tabbedPane.setPreferredSize(new java.awt.Dimension(900, 585));

        pnlAdminControls.setBackground(new java.awt.Color(248, 247, 244));

        jPanel3.setBackground(new java.awt.Color(133, 169, 143));
        jPanel3.setMaximumSize(new java.awt.Dimension(200, 250));
        jPanel3.setMinimumSize(new java.awt.Dimension(200, 250));

        lblBrandInfo.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        lblBrandInfo.setForeground(new java.awt.Color(248, 247, 244));
        lblBrandInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBrandInfo.setText("Our Brand");

        txtBrandInfo.setEditable(false);
        txtBrandInfo.setBackground(new java.awt.Color(248, 247, 244));
        txtBrandInfo.setColumns(20);
        txtBrandInfo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtBrandInfo.setRows(5);
        txtBrandInfo.setText("We source our yarn from ethical loacl businesses and are committed to creating, producing and\nselling ethically sourced products. Our pledge to produce long lasting and ethically sound \nproducts are a strong commitment to our customers.");
        txtBrandInfo.setAutoscrolls(false);
        jScrollPane4.setViewportView(txtBrandInfo);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.LEADING)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(164, 164, 164)
                        .add(lblBrandInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(37, 37, 37)
                        .add(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(lblBrandInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.UNRELATED)
                .add(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDisplayProducts.setBackground(new java.awt.Color(82, 91, 68));
        pnlDisplayProducts.setMaximumSize(new java.awt.Dimension(850, 250));
        pnlDisplayProducts.setMinimumSize(new java.awt.Dimension(850, 250));
        pnlDisplayProducts.setPreferredSize(new java.awt.Dimension(850, 250));

        lblGrannyCardigan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/crocheters/resources/grannySweaterCardiganNew.jpg"))); // NOI18N

        lblHalfSweater.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHalfSweater.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/crocheters/resources/halfSweater.jpg"))); // NOI18N

        lblCosyGreenSweater.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCosyGreenSweater.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/crocheters/resources/cosyGreenSweater.jpg"))); // NOI18N

        lblGrannySquareCardigan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGrannySquareCardigan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/crocheters/resources/grannySquareCardigan.jpg"))); // NOI18N

        javax.swing.GroupLayout pnlDisplayProductsLayout = new javax.swing.GroupLayout(pnlDisplayProducts);
        pnlDisplayProducts.setLayout(pnlDisplayProductsLayout);
        pnlDisplayProductsLayout.setHorizontalGroup(
            pnlDisplayProductsLayout.createParallelGroup(javax.swing.GroupLayout.LEADING)
            .add(pnlDisplayProductsLayout.createSequentialGroup()
                .add(lblGrannyCardigan, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.RELATED)
                .add(lblHalfSweater, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .add(12, 12, 12)
                .add(lblCosyGreenSweater, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .add(12, 12, 12)
                .add(lblGrannySquareCardigan, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
        );
        pnlDisplayProductsLayout.setVerticalGroup(
            pnlDisplayProductsLayout.createParallelGroup(javax.swing.GroupLayout.LEADING)
            .add(lblGrannyCardigan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(javax.swing.GroupLayout.TRAILING, lblCosyGreenSweater, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(lblGrannySquareCardigan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(javax.swing.GroupLayout.TRAILING, lblHalfSweater, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlAdminControlsLayout = new javax.swing.GroupLayout(pnlAdminControls);
        pnlAdminControls.setLayout(pnlAdminControlsLayout);
        pnlAdminControlsLayout.setHorizontalGroup(
            pnlAdminControlsLayout.createParallelGroup(javax.swing.GroupLayout.LEADING)
            .add(pnlAdminControlsLayout.createSequentialGroup()
                .add(pnlAdminControlsLayout.createParallelGroup(javax.swing.GroupLayout.LEADING)
                    .add(pnlAdminControlsLayout.createSequentialGroup()
                        .add(27, 27, 27)
                        .add(pnlDisplayProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .add(pnlAdminControlsLayout.createSequentialGroup()
                        .add(98, 98, 98)
                        .add(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        pnlAdminControlsLayout.setVerticalGroup(
            pnlAdminControlsLayout.createParallelGroup(javax.swing.GroupLayout.LEADING)
            .add(pnlAdminControlsLayout.createSequentialGroup()
                .add(30, 30, 30)
                .add(pnlDisplayProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .add(41, 41, 41)
                .add(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Admin Controls", pnlAdminControls);

        pnlAllproducts.setBackground(new java.awt.Color(82, 91, 68));

        tblProducts.setBackground(new java.awt.Color(248, 247, 244));
        tblProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Product ID", "Product Name", "Category", "Yarn Type", "Repairable", "Description", "Price", "Stock", "Date Added"
            }
        ));
        jScrollPane1.setViewportView(tblProducts);

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(248, 247, 244));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Our Products");

        javax.swing.GroupLayout pnlAllproductsLayout = new javax.swing.GroupLayout(pnlAllproducts);
        pnlAllproducts.setLayout(pnlAllproductsLayout);
        pnlAllproductsLayout.setHorizontalGroup(
            pnlAllproductsLayout.createParallelGroup(javax.swing.GroupLayout.LEADING)
            .add(pnlAllproductsLayout.createSequentialGroup()
                .add(pnlAllproductsLayout.createParallelGroup(javax.swing.GroupLayout.LEADING)
                    .add(pnlAllproductsLayout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 862, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .add(pnlAllproductsLayout.createSequentialGroup()
                        .add(249, 249, 249)
                        .add(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        pnlAllproductsLayout.setVerticalGroup(
            pnlAllproductsLayout.createParallelGroup(javax.swing.GroupLayout.LEADING)
            .add(pnlAllproductsLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.RELATED)
                .add(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        tabbedPane.addTab("All Products", pnlAllproducts);

        pnlAddproducts.setBackground(new java.awt.Color(248, 247, 244));
        pnlAddproducts.setMaximumSize(new java.awt.Dimension(900, 550));
        pnlAddproducts.setMinimumSize(new java.awt.Dimension(900, 550));
        pnlAddproducts.setPreferredSize(new java.awt.Dimension(900, 550));

        pnlForm.setBackground(new java.awt.Color(82, 91, 68));

        txtProdid.setBackground(new java.awt.Color(248, 247, 244));
        txtProdid.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Product ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        txtProdid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdidActionPerformed(evt);
            }
        });

        txtProdName.setBackground(new java.awt.Color(248, 247, 244));
        txtProdName.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Product Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        txtProdName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdNameActionPerformed(evt);
            }
        });

        txtPrice.setBackground(new java.awt.Color(248, 247, 244));
        txtPrice.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Price", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });

        spinStock.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Stock", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(153, 153, 153))); // NOI18N

        btnUpdate.setBackground(new java.awt.Color(133, 169, 143));
        btnUpdate.setText("Update Product");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(133, 169, 143));
        btnAdd.setText("Add Product");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(133, 169, 143));
        btnDelete.setText("Delete Product");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        checkRepair.setBackground(new java.awt.Color(248, 247, 244));
        checkRepair.setText("Repairable");

        boxCategory.setBackground(new java.awt.Color(248, 247, 244));
        boxCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sweater", "Scarf", "Cardigan" }));
        boxCategory.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Category", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(153, 153, 153))); // NOI18N

        boxYarnType.setBackground(new java.awt.Color(248, 247, 244));
        boxYarnType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cotton", "Wool", "Acrylic", "Chunky", "Cashmere" }));
        boxYarnType.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Yarn Type", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(153, 153, 153))); // NOI18N

        txtDescription.setBackground(new java.awt.Color(248, 247, 244));
        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        txtDescription.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Description", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(153, 153, 153))); // NOI18N
        jScrollPane2.setViewportView(txtDescription);

        javax.swing.GroupLayout pnlFormLayout = new javax.swing.GroupLayout(pnlForm);
        pnlForm.setLayout(pnlFormLayout);
        pnlFormLayout.setHorizontalGroup(
            pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.LEADING)
            .add(javax.swing.GroupLayout.TRAILING, pnlFormLayout.createSequentialGroup()
                .add(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.LEADING)
                    .add(pnlFormLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .add(98, 98, 98)
                        .add(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .add(pnlFormLayout.createSequentialGroup()
                        .add(105, 105, 105)
                        .add(checkRepair, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .add(57, 57, 57)
                        .add(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(spinStock, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .add(34, 34, 34)))
                .add(90, 90, 90))
            .add(pnlFormLayout.createSequentialGroup()
                .add(47, 47, 47)
                .add(txtProdid, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .add(34, 34, 34)
                .add(txtProdName, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .add(37, 37, 37)
                .add(boxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .add(40, 40, 40)
                .add(boxYarnType, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
            .add(javax.swing.GroupLayout.TRAILING, pnlFormLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .add(200, 200, 200))
        );
        pnlFormLayout.setVerticalGroup(
            pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.LEADING)
            .add(pnlFormLayout.createSequentialGroup()
                .add(70, 70, 70)
                .add(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.TRAILING)
                    .add(pnlFormLayout.createSequentialGroup()
                        .add(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.BASELINE)
                            .add(boxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .add(txtProdName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .add(txtProdid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .add(boxYarnType, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .add(45, 45, 45)
                        .add(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.TRAILING)
                            .add(checkRepair, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .add(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .add(spinStock, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.RELATED, 42, Short.MAX_VALUE)
                .add(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .add(29, 29, 29)
                .add(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.BASELINE)
                    .add(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .add(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .add(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .add(50, 50, 50))
        );

        javax.swing.GroupLayout pnlAddproductsLayout = new javax.swing.GroupLayout(pnlAddproducts);
        pnlAddproducts.setLayout(pnlAddproductsLayout);
        pnlAddproductsLayout.setHorizontalGroup(
            pnlAddproductsLayout.createParallelGroup(javax.swing.GroupLayout.LEADING)
            .add(pnlAddproductsLayout.createSequentialGroup()
                .add(97, 97, 97)
                .add(pnlForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );
        pnlAddproductsLayout.setVerticalGroup(
            pnlAddproductsLayout.createParallelGroup(javax.swing.GroupLayout.LEADING)
            .add(pnlAddproductsLayout.createSequentialGroup()
                .add(25, 25, 25)
                .add(pnlForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Add Products", pnlAddproducts);

        javax.swing.GroupLayout pnlTabLayout = new javax.swing.GroupLayout(pnlTab);
        pnlTab.setLayout(pnlTabLayout);
        pnlTabLayout.setHorizontalGroup(
            pnlTabLayout.createParallelGroup(javax.swing.GroupLayout.LEADING)
            .add(pnlTabLayout.createSequentialGroup()
                .add(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 899, javax.swing.GroupLayout.PREFERRED_SIZE)
                .add(0, 1, Short.MAX_VALUE))
        );
        pnlTabLayout.setVerticalGroup(
            pnlTabLayout.createParallelGroup(javax.swing.GroupLayout.LEADING)
            .add(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
        );

        lblTagline.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        lblTagline.setForeground(new java.awt.Color(248, 247, 244));
        lblTagline.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTagline.setText("Made With The Touch of Hand");

        btnLogout.setBackground(new java.awt.Color(133, 169, 143));
        btnLogout.setText("Log-Out");

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.LEADING)
            .add(pnlTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(pnlMainLayout.createSequentialGroup()
                .add(230, 230, 230)
                .add(lblTagline, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .add(23, 23, 23))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.LEADING)
            .add(javax.swing.GroupLayout.TRAILING, pnlMainLayout.createSequentialGroup()
                .add(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.LEADING)
                    .add(pnlMainLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(lblTagline)
                        .addPreferredGap(javax.swing.LayoutStyle.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(javax.swing.GroupLayout.TRAILING, pnlMainLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(btnLogout)
                        .add(18, 18, 18)))
                .add(pnlTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlLogin.setBackground(new java.awt.Color(82, 91, 68));
        pnlLogin.setMaximumSize(new java.awt.Dimension(900, 600));
        pnlLogin.setMinimumSize(new java.awt.Dimension(900, 600));
        pnlLogin.setPreferredSize(new java.awt.Dimension(900, 600));

        pnlLoginInfo.setBackground(new java.awt.Color(248, 247, 244));
        pnlLoginInfo.setMaximumSize(new java.awt.Dimension(450, 580));
        pnlLoginInfo.setMinimumSize(new java.awt.Dimension(450, 580));
        pnlLoginInfo.setPreferredSize(new java.awt.Dimension(450, 580));

        lblSignin.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        lblSignin.setForeground(new java.awt.Color(82, 91, 68));
        lblSignin.setText("Sign-In to Shop");

        btnLogin.setBackground(new java.awt.Color(133, 169, 143));
        btnLogin.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        btnLogin.setText("Log-In");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        txtUserName.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User-Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(82, 91, 68))); // NOI18N
        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });

        lblLoginInfo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblLoginInfo.setForeground(new java.awt.Color(82, 91, 68));
        lblLoginInfo.setText("Please enter user-name and password!");

        lblForgotPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblForgotPassword.setForeground(new java.awt.Color(82, 91, 68));
        lblForgotPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblForgotPassword.setText("Forgot Password?");

        txtPassword.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(82, 91, 68))); // NOI18N
        txtPassword.setMaximumSize(new java.awt.Dimension(64, 39));
        txtPassword.setMinimumSize(new java.awt.Dimension(64, 39));
        txtPassword.setPreferredSize(new java.awt.Dimension(64, 39));

        javax.swing.GroupLayout pnlLoginInfoLayout = new javax.swing.GroupLayout(pnlLoginInfo);
        pnlLoginInfo.setLayout(pnlLoginInfoLayout);
        pnlLoginInfoLayout.setHorizontalGroup(
            pnlLoginInfoLayout.createParallelGroup(javax.swing.GroupLayout.LEADING)
            .add(pnlLoginInfoLayout.createSequentialGroup()
                .add(pnlLoginInfoLayout.createParallelGroup(javax.swing.GroupLayout.TRAILING)
                    .add(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .add(pnlLoginInfoLayout.createSequentialGroup()
                        .add(pnlLoginInfoLayout.createParallelGroup(javax.swing.GroupLayout.LEADING)
                            .add(pnlLoginInfoLayout.createSequentialGroup()
                                .add(139, 139, 139)
                                .add(lblSignin))
                            .add(pnlLoginInfoLayout.createSequentialGroup()
                                .add(121, 121, 121)
                                .add(lblLoginInfo))
                            .add(pnlLoginInfoLayout.createSequentialGroup()
                                .add(127, 127, 127)
                                .add(pnlLoginInfoLayout.createParallelGroup(javax.swing.GroupLayout.LEADING)
                                    .add(lblForgotPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .add(javax.swing.GroupLayout.TRAILING, pnlLoginInfoLayout.createSequentialGroup()
                                        .add(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .add(15, 15, 15)))))
                        .add(17, 17, 17)))
                .addContainerGap(75, Short.MAX_VALUE))
            .add(javax.swing.GroupLayout.TRAILING, pnlLoginInfoLayout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(pnlLoginInfoLayout.createParallelGroup(javax.swing.GroupLayout.LEADING)
                    .add(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .add(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                .add(86, 86, 86))
        );
        pnlLoginInfoLayout.setVerticalGroup(
            pnlLoginInfoLayout.createParallelGroup(javax.swing.GroupLayout.LEADING)
            .add(pnlLoginInfoLayout.createSequentialGroup()
                .add(92, 92, 92)
                .add(lblSignin, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.RELATED)
                .add(lblLoginInfo)
                .add(23, 23, 23)
                .add(lblError)
                .add(27, 27, 27)
                .add(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .add(64, 64, 64)
                .add(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(lblForgotPassword)
                .addPreferredGap(javax.swing.LayoutStyle.UNRELATED)
                .add(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/crocheters/resources/loginpanel.jpg"))); // NOI18N

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.LEADING)
            .add(javax.swing.GroupLayout.TRAILING, pnlLoginLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .add(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .add(34, 34, 34)
                .add(pnlLoginInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.LEADING)
            .add(pnlLoginLayout.createSequentialGroup()
                .addContainerGap()
                .add(pnlLoginInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                .addContainerGap())
            .add(pnlLoginLayout.createSequentialGroup()
                .add(22, 22, 22)
                .add(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1130, 514));
        setMinimumSize(new java.awt.Dimension(1130, 514));
        setPreferredSize(new java.awt.Dimension(1130, 514));
        setSize(new java.awt.Dimension(1600, 870));

        pnlLoadScreen.setBackground(new java.awt.Color(82, 91, 68));
        pnlLoadScreen.setMaximumSize(new java.awt.Dimension(900, 600));
        pnlLoadScreen.setMinimumSize(new java.awt.Dimension(900, 600));
        pnlLoadScreen.setPreferredSize(new java.awt.Dimension(900, 600));

        lblLoading.setForeground(new java.awt.Color(248, 247, 244));
        lblLoading.setText("Loading.....");

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/crocheters/resources/theYarnestLogo (1).png"))); // NOI18N

        lblLoading2.setForeground(new java.awt.Color(248, 247, 244));
        lblLoading2.setText("THE YARNEST");

        lblLoading5.setForeground(new java.awt.Color(248, 247, 244));
        lblLoading5.setText("©THE YARNEST 2024");

        javax.swing.GroupLayout pnlLoadScreenLayout = new javax.swing.GroupLayout(pnlLoadScreen);
        pnlLoadScreen.setLayout(pnlLoadScreenLayout);
        pnlLoadScreenLayout.setHorizontalGroup(
            pnlLoadScreenLayout.createParallelGroup(javax.swing.GroupLayout.LEADING)
            .add(javax.swing.GroupLayout.TRAILING, pnlLoadScreenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .add(215, 215, 215))
            .add(pnlLoadScreenLayout.createSequentialGroup()
                .addContainerGap()
                .add(pnlLoadScreenLayout.createParallelGroup(javax.swing.GroupLayout.LEADING)
                    .add(pnlLoadScreenLayout.createSequentialGroup()
                        .add(0, 233, Short.MAX_VALUE)
                        .add(pnlLoadScreenLayout.createParallelGroup(javax.swing.GroupLayout.TRAILING)
                            .add(lblLoading)
                            .add(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .add(228, 228, 228))
                    .add(pnlLoadScreenLayout.createSequentialGroup()
                        .add(pnlLoadScreenLayout.createParallelGroup(javax.swing.GroupLayout.LEADING)
                            .add(lblLoading5, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .add(lblLoading2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlLoadScreenLayout.setVerticalGroup(
            pnlLoadScreenLayout.createParallelGroup(javax.swing.GroupLayout.LEADING)
            .add(javax.swing.GroupLayout.TRAILING, pnlLoadScreenLayout.createSequentialGroup()
                .add(lblLoading2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.RELATED, 52, Short.MAX_VALUE)
                .add(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.RELATED)
                .add(lblLoading, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .add(31, 31, 31)
                .add(lblLoading5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.LEADING)
            .add(javax.swing.GroupLayout.TRAILING, pnlLoadScreen, javax.swing.GroupLayout.DEFAULT_SIZE, 1130, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(pnlLoadScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//method to add panels and layout to the frame
    private void layoutInitialize() {
        cardLayout = new java.awt.CardLayout();
        getContentPane().setLayout(cardLayout);
        
        
        

        // Add panels with unique identifiers
        getContentPane().add(pnlLoadScreen, "LoadScreen");
        getContentPane().add(pnlLogin, "LoginScreen");
        getContentPane().add(pnlMain, "MainScreen");

        // Start with the loading screen
        cardLayout.show(getContentPane(), "LoadScreen");
    }
    
    //method to initialize data
    private void dataInitialize(){
        productList = new LinkedList(); 
        
        
    }
    
    // Method to simulate loading progress
    private void forProgressBar() {
        javax.swing.SwingWorker<Void, Integer> worker = new javax.swing.SwingWorker<>() {
            @Override
            protected Void doInBackground() throws Exception {
                for (int i = 0; i <= 100; i++) {
                    Thread.sleep(30); // Simulated delay for progress bar
                    publish(i);
                }
                return null;
            }

            @Override
            protected void process(java.util.List<Integer> chunks) {
                int progress = chunks.get(chunks.size() - 1);
                progressBar.setValue(progress);
            }

            @Override
            protected void done() {
                loadScreen("LoginScreen"); // Switch to login screen
            }
        };
        worker.execute();
    }
    
    // Method to add the products data into the table
    private void addProduct(crochetModel product) {
        productList.add(product);
        DefaultTableModel model = (DefaultTableModel) tblProducts.getModel();
        model.addRow(new Object[]{
            product.getProdId(), product.getProdName(), product.getCategory(),product.getYarnType(), product.isRepairable(),product.getDescription(),  product.getPrice(), product.getStock(), product.getDateAdded(),
        });
    }
    
    // Method to switch screens from load screen to log-in screen
    private void loadScreen(String screenName) {
        cardLayout.show(getContentPane(), screenName);
    }
    
    private void txtProdidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdidActionPerformed

    private void txtProdNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdNameActionPerformed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // To add the products from the form into the linkedlist
        int productId = Integer.parseInt(txtProdid.getText());
        String productName = txtProdName.getText();
        String category = (String) boxCategory.getSelectedItem();
        String yarnType = (String) boxYarnType.getSelectedItem();
        boolean repairable = checkRepair.isSelected();
        String description = txtDescription.getText();
        float price = Float.parseFloat(txtPrice.getText());
        int stock = (int) spinStock.getValue();
        
        SimpleDateFormat formatDate = new SimpleDateFormat("yyyy-MM-dd");
        String currentDate = formatDate.format(new Date());
        
        crochetModel product = new crochetModel(productId, productName, category, yarnType, repairable, description, price, stock, currentDate);
        addProduct(product);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // Get the input from log-in page
        String userName = txtUserName.getText();
        String password = new String(txtPassword.getPassword());

        // Check if fields are empty
        if (userName.isEmpty() || password.isEmpty()) {
            lblError.setText("Please enter your username and password!");
        } // Check username and password
        else if (!userName.equals("admin") || !password.equals("admin")) {
            lblError.setText("Username and password don't match!!!");
        } // Proceed to load the main screen after datas are validated
        else {
            lblError.setText(""); // Clear previous error messages
            loadScreen("MainScreen"); // Load main screen
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crochetApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crochetApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crochetApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crochetApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new crochetApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxCategory;
    private javax.swing.JComboBox<String> boxYarnType;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox checkRepair;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblBrandInfo;
    private javax.swing.JLabel lblCosyGreenSweater;
    private javax.swing.JLabel lblError;
    private javax.swing.JLabel lblForgotPassword;
    private javax.swing.JLabel lblGrannyCardigan;
    private javax.swing.JLabel lblGrannySquareCardigan;
    private javax.swing.JLabel lblHalfSweater;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblLoading;
    private javax.swing.JLabel lblLoading2;
    private javax.swing.JLabel lblLoading5;
    private javax.swing.JLabel lblLoginInfo;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblSignin;
    private javax.swing.JLabel lblTagline;
    private javax.swing.JPanel pnlAddproducts;
    private javax.swing.JPanel pnlAdminControls;
    private javax.swing.JPanel pnlAllproducts;
    private javax.swing.JPanel pnlDisplayProducts;
    private javax.swing.JPanel pnlForm;
    private javax.swing.JPanel pnlLoadScreen;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlLoginInfo;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlTab;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JSpinner spinStock;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTable tblProducts;
    private javax.swing.JTextArea txtBrandInfo;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtProdName;
    private javax.swing.JTextField txtProdid;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
